server:
  port: 9005

spring:
  application:
    name: supplier-service
  datasource:
    url: jdbc:postgresql://localhost:5432/supplier
    username: psqlRoot
    password: psqlPassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9101/eureka